### ISSUE TITLE
DTA cancells downloads when connection drops

### ISSUE THREAD

**Issue by laundmo** [downthemall/downthemall-legacy#216]
### Your DownThemAll! and Browser Version and Language and Operating System
dta 3.0.8; Firefox 52.0.2 (32-Bit); English; windows10 (64bit)

### Expected Behavior
if bandwidth drops continue downloading at very slow speed.

### Actual Behavior
cancells download and marks it as server issue.

### Steps To Reproduce
i dont really know. a connection that slows extremly down or a connection that you cane kill the bandwidth. 

FIX:
maybe add an dont cancell option that you cane enable to stop DTA from deleating the .part and cancelling download?

**Comment by AlexBeLi** [comment]
[http://www.downthemall.net/re-downthemall-and-webextensions-or-why-why-i-am-done-with-mozilla/](http://www.downthemall.net/re-downthemall-and-webextensions-or-why-why-i-am-done-with-mozilla/)

**Comment by Shea690901** [comment]
It seems to me to be a problem for EVERY error encountered...
When most times it would be enough to try again!
And even a 403 (missing file) can be retried after providing a new url (some sites move their files on a more or less regular basis)...
So why delete the partitial downloads at all?
Why not try again or ask for user intervention if the error persists?

I´ve got a rather unstable umts/gprs connection only and ot not funny to see a several hundret MB download disappear with only a few KB missing, just because there was a glizch in the connection (happend not onöy once but several times, each time I could have provided the new URL within seconds)

**Comment by Infi220** [comment]
I agree and I think this is a huge problem when downloading a large file. This still happens in the latest build upon some errors. DTA shouldn't delete a partially downloaded file under any circumstances. Just pause it and let the user decide what they want to do. In many cases the user may want to keep that file and use it as partially complete (especially when downloading in 1 segment), or they may want to resume it later after the error is fixed, or they may want to add a new mirror link to bypass the error and continue downloading.
